
const products = [
  {
    product_code: "C1001",
    bar_code: "BARC1001",
    name: "Men's Formal Shirt",
    status: true,
    thumbnail: "https://example.com/images/formal-shirt.jpg",
    product_images: [
      "https://example.com/images/formal-shirt1.jpg",
      "https://example.com/images/formal-shirt2.jpg",
    ],
    product_video: "https://example.com/videos/formal-shirt.mp4",
    buy_price: 15.0,
    sell_price: 29.99,
    category_id: ["65f0cabcde1234567890abcd"],
    product_size: [
      {
        size: "65f0cabf1234567890abcdef",
        sell_price: 29.99,
      },
    ],
    product_color: ["65f0cad01234567890abcdee"],
    discount: 5,
    stock: 50,
    description: "Elegant formal shirt made from premium cotton fabric.",
    super_offer: false,
    slug: "mens-formal-shirt",
  },
  {
    product_code: "C1002",
    bar_code: "BARC1002",
    name: "Women's Casual T-Shirt",
    status: true,
    thumbnail: "https://example.com/images/casual-tshirt.jpg",
    product_images: [
      "https://example.com/images/casual-tshirt1.jpg",
      "https://example.com/images/casual-tshirt2.jpg",
    ],
    buy_price: 10.0,
    sell_price: 19.99,
    category_id: ["65f0cabcde1234567890abcd"],
    product_size: [
      {
        size: "65f0cabf1234567890abcdef",
        sell_price: 19.99,
      },
    ],
    product_color: ["65f0cad01234567890abcdee"],
    discount: 10,
    stock: 30,
    description: "Soft and comfortable cotton T-shirt for women.",
    super_offer: true,
    slug: "womens-casual-tshirt",
  },
  {
    product_code: "C1003",
    bar_code: "BARC1003",
    name: "Men's Denim Jeans",
    status: true,
    thumbnail: "https://example.com/images/denim-jeans.jpg",
    product_images: [
      "https://example.com/images/denim-jeans1.jpg",
      "https://example.com/images/denim-jeans2.jpg",
    ],
    buy_price: 25.0,
    sell_price: 45.99,
    category_id: ["65f0cabcde1234567890abcd"],
    product_size: [
      {
        size: "65f0cabf1234567890abcdef",
        sell_price: 45.99,
      },
    ],
    product_color: ["65f0cad01234567890abcdee"],
    discount: 12,
    stock: 40,
    description: "Slim-fit stretchable denim jeans for men.",
    super_offer: false,
    slug: "mens-denim-jeans",
  },
  {
    product_code: "C1004",
    bar_code: "BARC1004",
    name: "Women's Summer Dress",
    status: true,
    thumbnail: "https://example.com/images/summer-dress.jpg",
    product_images: [
      "https://example.com/images/summer-dress1.jpg",
      "https://example.com/images/summer-dress2.jpg",
    ],
    buy_price: 30.0,
    sell_price: 55.99,
    category_id: ["65f0cabcde1234567890abcd"],
    product_size: [
      {
        size: "65f0cabf1234567890abcdef",
        sell_price: 55.99,
      },
    ],
    product_color: ["65f0cad01234567890abcdee"],
    discount: 15,
    stock: 20,
    description: "Lightweight and breathable summer dress for women.",
    super_offer: false,
    slug: "womens-summer-dress",
  },
  {
    product_code: "C1005",
    bar_code: "BARC1005",
    name: "Men's Hooded Jacket",
    status: true,
    thumbnail: "https://example.com/images/hooded-jacket.jpg",
    product_images: [
      "https://example.com/images/hooded-jacket1.jpg",
      "https://example.com/images/hooded-jacket2.jpg",
    ],
    buy_price: 40.0,
    sell_price: 69.99,
    category_id: ["65f0cabcde1234567890abcd"],
    product_size: [
      {
        size: "65f0cabf1234567890abcdef",
        sell_price: 69.99,
      },
    ],
    product_color: ["65f0cad01234567890abcdee"],
    discount: 8,
    stock: 15,
    description: "Warm and stylish hooded jacket for men.",
    super_offer: false,
    slug: "mens-hooded-jacket",
  },
  {
    product_code: "C1006",
    bar_code: "BARC1006",
    name: "Women's Workout Leggings",
    status: true,
    thumbnail: "https://example.com/images/workout-leggings.jpg",
    product_images: [
      "https://example.com/images/workout-leggings1.jpg",
      "https://example.com/images/workout-leggings2.jpg",
    ],
    buy_price: 20.0,
    sell_price: 34.99,
    category_id: ["65f0cabcde1234567890abcd"],
    product_size: [
      {
        size: "65f0cabf1234567890abcdef",
        sell_price: 34.99,
      },
    ],
    product_color: ["65f0cad01234567890abcdee"],
    discount: 10,
    stock: 25,
    description: "Stretchable and breathable workout leggings for women.",
    super_offer: true,
    slug: "womens-workout-leggings",
  },
  {
    product_code: "C1007",
    bar_code: "BARC1007",
    name: "Men's Polo T-Shirt",
    status: true,
    thumbnail: "https://example.com/images/polo-tshirt.jpg",
    product_images: [
      "https://example.com/images/polo-tshirt1.jpg",
      "https://example.com/images/polo-tshirt2.jpg",
    ],
    buy_price: 12.0,
    sell_price: 22.99,
    category_id: ["65f0cabcde1234567890abcd"],
    product_size: [
      {
        size: "65f0cabf1234567890abcdef",
        sell_price: 22.99,
      },
    ],
    product_color: ["65f0cad01234567890abcdee"],
    discount: 7,
    stock: 45,
    description: "Casual and comfortable polo T-shirt for men.",
    super_offer: false,
    slug: "mens-polo-tshirt",
  },
  {
    product_code: "C1008",
    bar_code: "BARC1008",
    name: "Women's Office Blazer",
    status: true,
    thumbnail: "https://example.com/images/office-blazer.jpg",
    product_images: [
      "https://example.com/images/office-blazer1.jpg",
      "https://example.com/images/office-blazer2.jpg",
    ],
    buy_price: 50.0,
    sell_price: 79.99,
    category_id: ["65f0cabcde1234567890abcd"],
    product_size: [
      {
        size: "65f0cabf1234567890abcdef",
        sell_price: 79.99,
      },
    ],
    product_color: ["65f0cad01234567890abcdee"],
    discount: 10,
    stock: 12,
    description: "Professional and stylish blazer for office wear.",
    super_offer: false,
    slug: "womens-office-blazer",
  },
];

module.exports = {products}